config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"
  resources :tasks, only: [:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, :deadline, presence: true

  scope :deadline, -> { order ('deadline ASC')}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:destroy]

  def index
    @tasks = Task.deadline
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to tasks_url, notice: 'Task successfully created.'
    else
      render :new
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task successfully destroyed.'
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:description, :title, :deadline)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkshopsTodo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<div class='main-content'>
  <div class='basic'>
    <p id='notice'><%= notice %></p>

    <h1>Tasks</h1>
    <div class='button'>
      <%= link_to 'New Task', new_task_path %>
    </div>
    <% @tasks.each do |task| %>
      <div class='list'>
        <table>
          <tbody>
            <tr><td><%= task.title %></td><td rowspan='2' class='right-link'><%= link_to 'Remove/Done', task, method: :delete, data: { confirm: 'Sure that you dont have to do this task?' } %></td></tr>
            <tr><td class='description'><%= task.description %></td></tr>
            <tr><td class='deadline'><%= task.deadline.strftime("%Y-%m-%d %H:%M:%S") if task.deadline %></td></tr>
          </tbody>
        </table>
      </div>
    <% end %>
    <br>
  </div>
</div>

app/views/tasks/new.html.erb
<div class='main-content'>
  <%= form_for(@task, url: tasks_path, html: { class: 'basic' }) do |f| %>

      <div class='title-row'>
        <h1>Add New Task</h1>
        <div class='button'>
          <%= link_to 'Tasks list', tasks_path %>
        </div>
        <% if @task.errors.any? %>
        <div>
          <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
        <% end %>
      </div>

      <div class='row field'>
        <label>
          <span>Title</span>
          <%= f.text_field :title %>
        </label>
      </div>

      <div class='row field'>
        <label>
          <span>Description</span>
          <%= f.text_area :description %>
        </label>
      </div>

      <div class='row field'>
        <label>
          <span>Deadline</span>
          <%= f.datetime_select :deadline %>
        </label>
      </div>

      <div class='row'>
        <button type="submit">Add it and Do it!</button>
      </div>
  <% end %>
</div>